Repository ec-europa/eiopa-styleguide, pull requests merged in 2018-05, with the labels that each got.

#1 feat(color): update color palette and related utilities
  src/systems/eiopa/_partials/_preview-palette.twig
  src/systems/eiopa/eiopa-base/variables/_colors.scss
  src/systems/eiopa/eiopa-style/eiopa-style-color/README.md
  src/systems/eiopa/eiopa-style/eiopa-style-color/colors.json
  src/systems/eiopa/eiopa-style/eiopa-style-color/eiopa-style-color.config.js
  src/systems/eiopa/eiopa-style/eiopa-style-color/package.json
  src/systems/eiopa/eiopa-utility/eiopa-utility-colorize/eiopa-utility-colorize.scss
  src/systems/eiopa/eiopa-utility/eiopa-utility-colorize/eiopa-utility-colorize.twig
  src/systems/eiopa/eiopa-utility/eiopa-utility-colorize/package.json
Labels: process:review needed

#5 feat(typography): update typography elements - INNO-1071
  src/systems/eiopa/eiopa-base/variables/_colors.scss
  src/systems/eiopa/eiopa-preset/eiopa-preset-website/build/styles/ecl-eiopa-preset-website.css
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-font/README.md
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/README.md
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/_mixins.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/eiopa-style-typography-heading--editor.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/eiopa-style-typography-heading.config.js
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/eiopa-style-typography-heading.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/test/spec/screenshots/reference/headings/Windows 10_Chrome_v60.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/test/spec/screenshots/reference/headings/Windows 7_Firefox_v54.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/test/spec/screenshots/reference/headings/Windows 7_IE_v11.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-heading/test/spec/screenshots/reference/headings/macOS 10.12_Safari_v11.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-list/_mixins.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-list/eiopa-style-typography-list--editor.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-list/eiopa-style-typography-list.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-list/test/spec/screenshots/reference/lists/Windows 10_Chrome_v60.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-list/test/spec/screenshots/reference/lists/Windows 7_Firefox_v54.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-list/test/spec/screenshots/reference/lists/Windows 7_IE_v11.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-list/test/spec/screenshots/reference/lists/macOS 10.12_Safari_v11.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-paragraph/README.md
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-paragraph/_mixins.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-paragraph/eiopa-style-typography-paragraph--editor.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-paragraph/eiopa-style-typography-paragraph.scss
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-paragraph/test/spec/screenshots/reference/paragraphs/Windows 10_Chrome_v60.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-paragraph/test/spec/screenshots/reference/paragraphs/Windows 7_Firefox_v54.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-paragraph/test/spec/screenshots/reference/paragraphs/Windows 7_IE_v11.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography-paragraph/test/spec/screenshots/reference/paragraphs/macOS 10.12_Safari_v11.png
  src/systems/eiopa/eiopa-style/eiopa-style-typography/eiopa-style-typography/eiopa-style-typography.scss
Labels: process:review needed, tag: new feature

#3 refactor(theme): update links - INNO-1050
  README.md
  docs/01-overview.md
  docs/03-javascript.md
  docs/03-presets.md
  docs/04-documentation.md
  docs/05-systems.md
  docs/06-presets.md
  docs/07-developers.md
  docs/conventions/git.md
  src/systems/eiopa/eiopa-preset/eiopa-preset-base/README.md
  src/systems/eiopa/eiopa-preset/eiopa-preset-full/README.md
  src/systems/eiopa/eiopa-preset/eiopa-preset-website/.gitignore
  src/systems/eiopa/eiopa-preset/eiopa-preset-website/README.md
  src/systems/eiopa/eiopa-preset/eiopa-preset-website/build/fonts/europa-icons/europa-icons.eot
  src/systems/eiopa/eiopa-preset/eiopa-preset-website/build/fonts/europa-icons/europa-icons.svg
  src/systems/eiopa/eiopa-preset/eiopa-preset-website/build/fonts/europa-icons/europa-icons.ttf
  src/systems/eiopa/eiopa-preset/eiopa-preset-website/build/fonts/europa-icons/europa-icons.woff
  src/systems/eiopa/eiopa-preset/eiopa-preset-website/build/styles/ecl-eiopa-preset-website.css
  tools/eiopa-styleguide/fractal.js
  tools/eiopa-styleguide/theme-overrides/partials/footer_links.nunj
  tools/eiopa-styleguide/theme-overrides/partials/footer_title.nunj
  tools/eiopa-styleguide/theme-overrides/partials/header_breadcrumb.nunj
Labels: tag: enhancement

#8 feat(search-form): add search-form - INNO-1055
  src/systems/eiopa/eiopa-component/eiopa-component-form-form-group/README.md
  src/systems/eiopa/eiopa-component/eiopa-component-form-form-group/eiopa-component-form-form-group.config.js
  src/systems/eiopa/eiopa-component/eiopa-component-form-form-group/eiopa-component-form-form-group.scss
  src/systems/eiopa/eiopa-component/eiopa-component-form-form-group/eiopa-component-form-form-group.twig
  src/systems/eiopa/eiopa-component/eiopa-component-form-form-group/package.json
  src/systems/eiopa/eiopa-component/eiopa-component-form-text-input/README.md
  src/systems/eiopa/eiopa-component/eiopa-component-form-text-input/data/demo--default.js
  src/systems/eiopa/eiopa-component/eiopa-component-form-text-input/data/demo--disabled.js
  src/systems/eiopa/eiopa-component/eiopa-component-form-text-input/data/demo--with-error.js
  src/systems/eiopa/eiopa-component/eiopa-component-form-text-input/eiopa-component-form-text-input.config.js
  src/systems/eiopa/eiopa-component/eiopa-component-form-text-input/eiopa-component-form-text-input.scss
  src/systems/eiopa/eiopa-component/eiopa-component-form-text-input/eiopa-component-form-text-input.twig
  src/systems/eiopa/eiopa-component/eiopa-component-form-text-input/package.json
  src/systems/eiopa/eiopa-component/eiopa-component-search-form/README.md
  src/systems/eiopa/eiopa-component/eiopa-component-search-form/data/demo--default.js
  src/systems/eiopa/eiopa-component/eiopa-component-search-form/data/demo--internal.js
  src/systems/eiopa/eiopa-component/eiopa-component-search-form/eiopa-component-search-form.config.js
  src/systems/eiopa/eiopa-component/eiopa-component-search-form/eiopa-component-search-form.scss
  src/systems/eiopa/eiopa-component/eiopa-component-search-form/eiopa-component-search-form.twig
  src/systems/eiopa/eiopa-component/eiopa-component-search-form/package.json
  src/systems/eiopa/eiopa-component/eiopa-component-search-form/test/.gitkeep
  src/systems/eiopa/eiopa-preset/eiopa-preset-full/_imports.scss
Labels: process:review needed, tag: new feature

#9 feat(breadcrumb): add component - INNO-1065
  src/systems/eiopa/eiopa-component/eiopa-component-breadcrumb/README.md
  src/systems/eiopa/eiopa-component/eiopa-component-breadcrumb/data/demo.js
  src/systems/eiopa/eiopa-component/eiopa-component-breadcrumb/eiopa-component-breadcrumb.config.js
  src/systems/eiopa/eiopa-component/eiopa-component-breadcrumb/eiopa-component-breadcrumb.scss
  src/systems/eiopa/eiopa-component/eiopa-component-breadcrumb/eiopa-component-breadcrumb.twig
  src/systems/eiopa/eiopa-component/eiopa-component-breadcrumb/package.json
  src/systems/eiopa/eiopa-component/eiopa-component-link/eiopa-component-link.scss
  src/systems/eiopa/eiopa-preset/eiopa-preset-full/_imports.scss
Labels: process:review needed, tag: new feature
